backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor: 
     preview: false
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Lead Image", name: "lead_image", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Old Tags", name: "old_tags", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}

  - name: "projects" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Project" # Used in the UI, ie.: "New Post"
    folder: "_projects" # The path to the folder where the documents are stored
    sort: "title:asc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    editor: 
     preview: false
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Lead Image", name: "lead_image", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "string", required: false}
      - {label: "Weight", name: "weight", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "tags" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Tag" # Used in the UI, ie.: "New Post"
    folder: "_blog_tags" # The path to the folder where the documents are stored
    sort: "title:asc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    editor: 
     preview: false
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Link State", name: "link-state", widget: "string"}
      - {label: "Layout", name: "layout", widget: "string"}

  - name: "pages" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "page" # Used in UI, ie.: "New Page"
    folder: "_pages"
    sort: "title:asc" # default is title:asc
    create: true
    slug: "{{slug}}"
    editor: 
     preview: false
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      
